apiVersion: apps/v1
kind: Deployment
metadata:
  name: supporthr-api
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: api
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supporthr-worker
spec:
  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: worker
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 300m
              memory: 1Gi
            limits:
              cpu: "1"
              memory: 4Gi
