apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: supporthr-oci

resources:
  - namespace.yaml
  - ../../base
  - redis.yaml
  - ingress.yaml

images:
  - name: supporthr-backend
    newName: ghcr.io/techfutureaifpt/supporthr-backend
    newTag: replace-with-release-tag

patches:
  - path: config-patch.yaml
  - path: deployment-patch.yaml
  - path: autoscaling-delete.yaml
  - path: pdb-delete.yaml
