apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: supporthr-api
spec:
  minReplicas: 1
  maxReplicas: 3
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: supporthr-worker
spec:
  minReplicas: 1
  maxReplicas: 3
