apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: supporthr-local

resources:
  - namespace.yaml
  - ../../base
  - redis.yaml

secretGenerator:
  - name: supporthr-backend-secrets
    literals:
      - REDIS_INTERNAL_URL=redis://redis:6379/0

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: supporthr-backend
    newName: supporthr-backend
    newTag: local

patches:
  - path: deployment-patch.yaml
  - path: hpa-patch.yaml
