apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: supporthr-api
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.example.com
      secretName: supporthr-api-tls
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: supporthr-api
                port:
                  name: http
